/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.30
 * Generated at: 2020-03-20 08:01:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class regist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang = \"en\">\r\n");
      out.write("<!-- Basic -->\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("\r\n");
      out.write("<!-- Mobile Metas -->\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("<!-- Site Metas -->\r\n");
      out.write("<title>Freshshop - Ecommerce Bootstrap 4 HTML Template</title>\r\n");
      out.write("<meta name=\"keywords\" content=\"\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("<!-- Site Icons -->\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"images/favicon.ico\" type=\"image/x-icon\">\r\n");
      out.write("<link rel=\"apple-touch-icon\" href=\"images/apple-touch-icon.png\">\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("<!-- Site CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("<!-- Responsive CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/responsive.css\">\r\n");
      out.write("<!-- Custom CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/custom.css\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"//code.jquery.com/jquery.min.js\"></script>\r\n");
      out.write("   <script\r\n");
      out.write("      src=\"//maxcdn.bootstrapcdn.com/bootstrap/latest/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("   <style>\r\n");
      out.write("/* 사이드바 래퍼 스타일 */\r\n");
      out.write("#page-wrapper {\r\n");
      out.write("   padding-left: 250px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sidebar-wrapper {\r\n");
      out.write("   position: fixed;\r\n");
      out.write("   width: 250px;\r\n");
      out.write("   height: 100%;\r\n");
      out.write("   margin-left: -250px;\r\n");
      out.write("   background-color: #ffffff;\r\n");
      out.write("   overflow-x: hidden;\r\n");
      out.write("   overflow-y: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#page-content-wrapper {\r\n");
      out.write("   width: 100%;\r\n");
      out.write("   padding: 20px;\r\n");
      out.write("}\r\n");
      out.write("/* 사이드바 스타일 */\r\n");
      out.write(".sidebar-nav {\r\n");
      out.write("   width: 250px;\r\n");
      out.write("   margin-top: 150px;\r\n");
      out.write("   padding: 0;\r\n");
      out.write("   list-style: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar-nav li {\r\n");
      out.write("   text-indent: 1.5em;\r\n");
      out.write("   line-height: 2.8em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar-nav li a {\r\n");
      out.write("   display: block;\r\n");
      out.write("   text-decoration: none;\r\n");
      out.write("   color: #000000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar-nav li a:hover {\r\n");
      out.write("   color: #000000;\r\n");
      out.write("   background: rgb(255, 255, 255, 0.2);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar-nav>.sidebar-brand {\r\n");
      out.write("   font-size: 1.3em;\r\n");
      out.write("   line-height: 3em;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<!--[if lt IE 9]>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("<script src=\"https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("    function sample6_execDaumPostcode() {\r\n");
      out.write("        new daum.Postcode({\r\n");
      out.write("            oncomplete: function(data) {\r\n");
      out.write("                // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.\r\n");
      out.write("\r\n");
      out.write("                // 각 주소의 노출 규칙에 따라 주소를 조합한다.\r\n");
      out.write("                // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.\r\n");
      out.write("                var addr = ''; // 주소 변수\r\n");
      out.write("                var extraAddr = ''; // 참고항목 변수\r\n");
      out.write("\r\n");
      out.write("                //사용자가 선택한 주소 타입에 따라 해당 주소 값을 가져온다.\r\n");
      out.write("                if (data.userSelectedType === 'R') { // 사용자가 도로명 주소를 선택했을 경우\r\n");
      out.write("                    addr = data.roadAddress;\r\n");
      out.write("                } else { // 사용자가 지번 주소를 선택했을 경우(J)\r\n");
      out.write("                    addr = data.jibunAddress;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                // 사용자가 선택한 주소가 도로명 타입일때 참고항목을 조합한다.\r\n");
      out.write("                if(data.userSelectedType === 'R'){\r\n");
      out.write("                    // 법정동명이 있을 경우 추가한다. (법정리는 제외)\r\n");
      out.write("                    // 법정동의 경우 마지막 문자가 \"동/로/가\"로 끝난다.\r\n");
      out.write("                    if(data.bname !== '' && /[동|로|가]$/g.test(data.bname)){\r\n");
      out.write("                        extraAddr += data.bname;\r\n");
      out.write("                    }\r\n");
      out.write("                    // 건물명이 있고, 공동주택일 경우 추가한다.\r\n");
      out.write("                    if(data.buildingName !== '' && data.apartment === 'Y'){\r\n");
      out.write("                        extraAddr += (extraAddr !== '' ? ', ' + data.buildingName : data.buildingName);\r\n");
      out.write("                    }\r\n");
      out.write("                    // 표시할 참고항목이 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.\r\n");
      out.write("                    if(extraAddr !== ''){\r\n");
      out.write("                        extraAddr = ' (' + extraAddr + ')';\r\n");
      out.write("                    }\r\n");
      out.write("                    // 조합된 참고항목을 해당 필드에 넣는다.\r\n");
      out.write("                    document.getElementById(\"sample6_extraAddress\").value = extraAddr;\r\n");
      out.write("                \r\n");
      out.write("                } else {\r\n");
      out.write("                    document.getElementById(\"sample6_extraAddress\").value = '';\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                // 우편번호와 주소 정보를 해당 필드에 넣는다.\r\n");
      out.write("                document.getElementById('sample6_postcode').value = data.zonecode;\r\n");
      out.write("                document.getElementById(\"sample6_address\").value = addr;\r\n");
      out.write("                // 커서를 상세주소 필드로 이동한다.\r\n");
      out.write("                document.getElementById(\"sample6_detailAddress\").focus();\r\n");
      out.write("            }\r\n");
      out.write("        }).open();\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("      <header class=\"main-header\">\r\n");
      out.write("        <!-- Start Navigation -->\r\n");
      out.write("        <nav class=\"navbar navbar-expand-lg navbar-light bg-light navbar-default bootsnav\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <!-- Start Header Navigation -->\r\n");
      out.write("                <div class=\"navbar-header\">\r\n");
      out.write("                    <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbar-menu\" aria-controls=\"navbars-rs-food\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("                    <i class=\"fa fa-bars\"></i>\r\n");
      out.write("                </button>\r\n");
      out.write("                    <a class=\"navbar-brand\" href=\"mainPage.html\"><img src=\"images/logo.png\" class=\"logo\" alt=\"\"></a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- End Header Navigation -->\r\n");
      out.write("\r\n");
      out.write("                <!-- Collect the nav links, forms, and other content for toggling -->\r\n");
      out.write("                <div class=\"collapse navbar-collapse\" id=\"navbar-menu\">\r\n");
      out.write("                    <ul class=\"nav navbar-nav ml-auto\" data-in=\"fadeInDown\" data-out=\"fadeOutUp\">\r\n");
      out.write("                        \r\n");
      out.write("                        <ul class=\"nav navbar-nav ml-auto\" data-in=\"fadeInDown\" data-out=\"fadeOutUp\">\r\n");
      out.write("                       \r\n");
      out.write("                        <li class=\"nav-item\"><a class=\"nav-link\" href=\"board.jsp\">게시판</a></li>\r\n");
      out.write("                        \r\n");
      out.write("                        <li class=\"nav-item\"><a class=\"nav-link\" href=\"recipe_list.html\">레시피</a></li>\r\n");
      out.write("                        <li class=\"nav-item\"><a class=\"nav-link\" href=\"ingredientList.html\">식재료</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                        <li class=\"nav-item\"><a class=\"nav-link\" href=\"login.html\">로그인</a></li>\r\n");
      out.write("                        \r\n");
      out.write("                        <li class=\"nav-item\"><a class=\"nav-link\" href=\"myPage.html\">마이페이지</a></li>\r\n");
      out.write("                        <li class=\"nav-item\"><a class=\"nav-link\" href=\"cart.html\">장바구니</a></li>\r\n");
      out.write("                        <div class=\"collapse navbar-collapse\" id=\"navbar-menu\">\r\n");
      out.write("                    \r\n");
      out.write("                            \r\n");
      out.write("                    \r\n");
      out.write("                            <ul class=\"nav navbar-nav ml-auto\" data-in=\"fadeInDown\" data-out=\"fadeOutUp\">\r\n");
      out.write("                        <form action=\"#\">\r\n");
      out.write("                                <input class=\"form-control\" placeholder=\"Search here...\" type=\"text\">\r\n");
      out.write("                            \r\n");
      out.write("                                \r\n");
      out.write("                            </form>\r\n");
      out.write("                        <button type=\"submit\"> <i class=\"fa fa-search\"></i> </button>\r\n");
      out.write("                        \r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- /.navbar-collapse -->\r\n");
      out.write("\r\n");
      out.write("                <!-- Start Atribute Navigation -->\r\n");
      out.write("                <div class=\"search-product\">\r\n");
      out.write("                            \r\n");
      out.write("                        </div>\r\n");
      out.write("                <!-- End Atribute Navigation -->\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("        </nav>\r\n");
      out.write("        <!-- End Navigation -->\r\n");
      out.write("    </header>\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("      <!-- 사이드바 -->\r\n");
      out.write("      <div id=\"sidebar-wrapper\">\r\n");
      out.write("         <ul class=\"sidebar-nav\">\r\n");
      out.write("\r\n");
      out.write("            <li><a href=\"#\">회원정보수정</a></li>\r\n");
      out.write("            <li><a href=\"#\">회원정보탈퇴</a></li>\r\n");
      out.write("            <li><a href=\"#\">장바구니목록</a></li>\r\n");
      out.write("            <li><a href=\"#\">판매관리페이지</a></li>\r\n");
      out.write("            <li><a href=\"#\">광고관리페이지</a></li>\r\n");
      out.write("            <li><a href=\"#\">회원정보관리페이지</a></li>\r\n");
      out.write("         </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- /사이드바 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <div class=\"contact-box-main\">\r\n");
      out.write("\r\n");
      out.write("         <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("               <div class=\"col-lg-8 col-sm-12\">\r\n");
      out.write("                  <div class=\"contact-form-right\">\r\n");
      out.write("                     <h2>회원가입</h2>\r\n");
      out.write("                     <p>회원정보 양식을 입력해주세요</p>\r\n");
      out.write("\r\n");
      out.write("                     <form id=\"contactForm\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                           <div class=\"col-md-12\">\r\n");
      out.write("                              아이디\r\n");
      out.write("                              <div class=\"form-group\">\r\n");
      out.write("                                 <input type=\"text\" class=\"form-control\" id=\"id\" name=\"id\"\r\n");
      out.write("                                    required data-error=\"아이디를 입력해주세요\"> <input\r\n");
      out.write("                                    type=\"button\" class=\"btn btn-default\" style=\"width: 20%;\"\r\n");
      out.write("                                    value=\"아이디중복확인\" onclick=\"duplicationId();\" />\r\n");
      out.write("                                 <div class=\"help-block with-errors\"></div>\r\n");
      out.write("                              </div>\r\n");
      out.write("                           </div>\r\n");
      out.write("                           <div class=\"col-md-12\">\r\n");
      out.write("                              이름\r\n");
      out.write("                              <div class=\"form-group\">\r\n");
      out.write("                                 <input type=\"text\" class=\"form-control\" id=\"name\" name=\"name\"\r\n");
      out.write("                                    required data-error=\"이름을 입력해주세요\">\r\n");
      out.write("                                 <div class=\"help-block with-errors\"></div>\r\n");
      out.write("                              </div>\r\n");
      out.write("                           </div>\r\n");
      out.write("\r\n");
      out.write("                           <div class=\"col-md-12\">\r\n");
      out.write("                              비밀번호\r\n");
      out.write("                              <div class=\"form-group\">\r\n");
      out.write("                                 <input type=\"password\" class=\"form-control\" id=\"password\"\r\n");
      out.write("                                    name=\"password\" required data-error=\"비밀번호를 입력해주세요\">\r\n");
      out.write("                                 <div class=\"help-block with-errors\"></div>\r\n");
      out.write("                              </div>\r\n");
      out.write("                           </div>\r\n");
      out.write("\r\n");
      out.write("                           <div class=\"col-md-12\">\r\n");
      out.write("                              비밀번호확인\r\n");
      out.write("                              <div class=\"form-group\">\r\n");
      out.write("                                 <input type=\"password\" class=\"form-control\" id=\"password\"\r\n");
      out.write("                                    name=\"password\" required data-error=\"비밀번호를 입력해주세요\">\r\n");
      out.write("                                 <div class=\"help-block with-errors\"></div>\r\n");
      out.write("                              </div>\r\n");
      out.write("                           </div>\r\n");
      out.write("\r\n");
      out.write("                           <div class=\"col-md-12\">\r\n");
      out.write("                              <div class=\"form-group\">\r\n");
      out.write("                                 휴대폰번호\r\n");
      out.write("                                 <div class=\"form-group\">\r\n");
      out.write("                                 <input type=\"text\" class=\"form-control\" id=\"phoneNumber\"\r\n");
      out.write("                                    name=\"phoneNumber\" required data-error=\"휴대폰번호를 입력해주세요\">\r\n");
      out.write("                                    <div class=\"help-block with-errors\"></div>\r\n");
      out.write("                                 </div>\r\n");
      out.write("                              </div>\r\n");
      out.write("                           </div>\r\n");
      out.write("                           \r\n");
      out.write("                           <div class=\"col-md-12\">\r\n");
      out.write("                              비밀번호질문\r\n");
      out.write("                              <div class=\"form-group\">\r\n");
      out.write("                                 <select name=\"passwdQ\" style=\"width: 400px; height: 35px;\">\r\n");
      out.write("                                    <option value=\"none\">선택</option>\r\n");
      out.write("                                    <option value=\"Q1\">자신이 처음 살았던 동네는?</option>\r\n");
      out.write("                                    <option value=\"Q2\">자신의 보물 1호는?</option>\r\n");
      out.write("                                    <option value=\"Q3\">자신이 가장좋아하는 음식은?</option>\r\n");
      out.write("                                    <option value=\"Q4\">자신이 가장좋아하는 운동은?</option>\r\n");
      out.write("                                    <option value=\"Q5\">자신이 감명깊게 읽은 책은?</option>\r\n");
      out.write("                                 </select>\r\n");
      out.write("                              </div>\r\n");
      out.write("                           </div>\r\n");
      out.write("\r\n");
      out.write("                           <div class=\"col-md-12\">\r\n");
      out.write("                              비밀번호질문답변\r\n");
      out.write("                              <div class=\"form-group\">\r\n");
      out.write("                                 <input type=\"text\" class=\"form-control\" id=\"password\"\r\n");
      out.write("                                    name=\"password\" required data-error=\"질문답변을 입력해주세요\">\r\n");
      out.write("                                 <div class=\"help-block with-errors\"></div>\r\n");
      out.write("                              </div>\r\n");
      out.write("                           </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                           <div class=\"col-md-12\">\r\n");
      out.write("                              회원주소<br>\r\n");
      out.write("                              <input type=\"text\" id=\"sample6_postcode\" placeholder=\"우편번호\">\r\n");
      out.write("                                        <input type=\"button\" onclick=\"sample6_execDaumPostcode()\" value=\"우편번호 찾기\"><br>\r\n");
      out.write("                                        <input type=\"text\" id=\"sample6_address\" placeholder=\"주소\"><br>\r\n");
      out.write("                                        <input type=\"text\" id=\"sample6_detailAddress\" placeholder=\"상세주소\">\r\n");
      out.write("                                        \r\n");
      out.write("                                       \r\n");
      out.write("                           </div>\r\n");
      out.write("                           <div class=\"col-md-12\">\r\n");
      out.write("                              생년월일\r\n");
      out.write("                              <div class=\"form-group\">\r\n");
      out.write("                                 <input type=\"text\" class=\"form-control\" id=\"birthday\"\r\n");
      out.write("                                    name=\"birthday\" required data-error=\"생년월일을 입력해주세요\">ex)\r\n");
      out.write("                                 19990101\r\n");
      out.write("\r\n");
      out.write("                                 <div class=\"help-block with-errors\"></div>\r\n");
      out.write("                              </div>\r\n");
      out.write("                           </div>\r\n");
      out.write("\r\n");
      out.write("                           <div class=\"col-md-12\">\r\n");
      out.write("                              <div class=\"form-group\">\r\n");
      out.write("                                 이메일\r\n");
      out.write("                                 <div class=\"form-group\">\r\n");
      out.write("                                    <input type=\"text\" id=\"email\" name=\"email\" required\r\n");
      out.write("                                       data-error=\"이메일을 입력해주세요\">@ <select name=\"email\"\r\n");
      out.write("                                       style=\"width: 250px; height: 35px;\">\r\n");
      out.write("                                       <option value=\"none\">선택</option>\r\n");
      out.write("                                       <option value=\"email1\">gmail.com</option>\r\n");
      out.write("                                       <option value=\"email2\">naver.com</option>\r\n");
      out.write("                                       <option value=\"email3\">daum.net</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                    <div class=\"help-block with-errors\"></div>\r\n");
      out.write("                                 </div>\r\n");
      out.write("                                 <div class=\"submit-button text-center\">\r\n");
      out.write("                                    <button class=\"btn hvr-hover\" id=\"submit\" type=\"submit\"\r\n");
      out.write("                                       style=\"margin-right: 10px\";>회원가입</button>\r\n");
      out.write("                                    <button class=\"btn hvr-hover\" id=\"submit\" type=\"submit\"\r\n");
      out.write("                                       style=\"margin-left: 10px\">취소</button>\r\n");
      out.write("                                    <div id=\"msgSubmit\" class=\"h3 text-center hidden\"></div>\r\n");
      out.write("                                    <div class=\"clearfix\"></div>\r\n");
      out.write("                                 </div>\r\n");
      out.write("                              </div>\r\n");
      out.write("                           </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                     </form>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <!-- Start Footer  -->\r\n");
      out.write("      <footer>\r\n");
      out.write("         <div class=\"footer-main\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("               <div class=\"row\">\r\n");
      out.write("                  <div class=\"col-lg-4 col-md-12 col-sm-12\">\r\n");
      out.write("                     <div class=\"footer-top-box\">\r\n");
      out.write("                        <h3>운영시간</h3>\r\n");
      out.write("                        <ul class=\"list-time\">\r\n");
      out.write("                           <li>월요일 - 금요일: 08.00am to 05.00pm</li>\r\n");
      out.write("                           <li>토요일: 10.00am to 08.00pm</li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                     </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"col-lg-4 col-md-12 col-sm-12\">\r\n");
      out.write("                     <div class=\"footer-top-box\">\r\n");
      out.write("                        <h3>About 1인식탁</h3>\r\n");
      out.write("                        <p>1인식탁은 1인가구를 위한 레시피제공, 그에 띠른 식자재 제공 및 배달로 요리에 대한 접근을 쉽게\r\n");
      out.write("                           만들어주고자 하는 서비스입니다. 1인가구의 양에 맞춤한 용량으로 서비스를 제공합니다.</p>\r\n");
      out.write("                     </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"col-lg-4 col-md-12 col-sm-12\">\r\n");
      out.write("                     <div class=\"footer-link-contact\">\r\n");
      out.write("                        <h4>Contact Us</h4>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                           <li>\r\n");
      out.write("                              <p>\r\n");
      out.write("                                 <i class=\"fas fa-map-marker-alt\"></i>Address: Michael I. Days\r\n");
      out.write("                                 3756 <br>Preston Street Wichita,<br> KS 67213\r\n");
      out.write("                              </p>\r\n");
      out.write("                           </li>\r\n");
      out.write("                           <li>\r\n");
      out.write("                              <p>\r\n");
      out.write("                                 <i class=\"fas fa-phone-square\"></i>Phone: <a\r\n");
      out.write("                                    href=\"tel:+1-888705770\">+1-888 705 770</a>\r\n");
      out.write("                              </p>\r\n");
      out.write("                           </li>\r\n");
      out.write("                           <li>\r\n");
      out.write("                              <p>\r\n");
      out.write("                                 <i class=\"fas fa-envelope\"></i>Email: <a\r\n");
      out.write("                                    href=\"mailto:contactinfo@gmail.com\">contactinfo@gmail.com</a>\r\n");
      out.write("                              </p>\r\n");
      out.write("                           </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                     </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("      </footer>\r\n");
      out.write("      <!-- End Footer  -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <a href=\"#\" id=\"back-to-top\" title=\"Back to top\"\r\n");
      out.write("         style=\"display: none;\">&uarr;</a>\r\n");
      out.write("\r\n");
      out.write("      <!-- ALL JS FILES -->\r\n");
      out.write("      <script src=\"js/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("      <script src=\"js/popper.min.js\"></script>\r\n");
      out.write("      <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("      <!-- ALL PLUGINS -->\r\n");
      out.write("      <script src=\"js/jquery.superslides.min.js\"></script>\r\n");
      out.write("      <script src=\"js/bootstrap-select.js\"></script>\r\n");
      out.write("      <script src=\"js/inewsticker.js\"></script>\r\n");
      out.write("      <script src=\"js/bootsnav.js.\"></script>\r\n");
      out.write("      <script src=\"js/images-loded.min.js\"></script>\r\n");
      out.write("      <script src=\"js/isotope.min.js\"></script>\r\n");
      out.write("      <script src=\"js/owl.carousel.min.js\"></script>\r\n");
      out.write("      <script src=\"js/baguetteBox.min.js\"></script>\r\n");
      out.write("      <script src=\"js/form-validator.min.js\"></script>\r\n");
      out.write("      <script src=\"js/contact-form-script.js\"></script>\r\n");
      out.write("      <script src=\"js/custom.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
